import http from "node:http";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import pg from "pg";

const PORT=Number(process.env.PORT||10000);
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==="true"?{rejectUnauthorized:false}:undefined}):null;
const W=[["01","أدرار"],["02","الشلف"],["03","الأغواط"],["04","أم البواقي"],["05","باتنة"],["06","بجاية"],["07","بسكرة"],["08","بشار"],["09","البليدة"],["10","البويرة"],["11","تمنراست"],["12","تبسة"],["13","تلمسان"],["14","تيارت"],["15","تيزي وزو"],["16","الجزائر"],["17","الجلفة"],["18","جيجل"],["19","سطيف"],["20","سعيدة"],["21","سكيكدة"],["22","سيدي بلعباس"],["23","عنابة"],["24","قالمة"],["25","قسنطينة"],["26","المدية"],["27","مستغانم"],["28","المسيلة"],["29","معسكر"],["30","ورقلة"],["31","وهران"],["32","البيض"],["33","إليزي"],["34","برج بوعريريج"],["35","بومرداس"],["36","الطارف"],["37","تندوف"],["38","تيسمسيلت"],["39","الوادي"],["40","خنشلة"],["41","سوق أهراس"],["42","تيبازة"],["43","ميلة"],["44","عين الدفلى"],["45","النعامة"],["46","عين تموشنت"],["47","غرداية"],["48","غليزان"],["49","تيميمون"],["50","برج باجي مختار"],["51","أولاد جلال"],["52","بني عباس"],["53","عين صالح"],["54","عين قزام"],["55","تقرت"],["56","جانت"],["57","المغير"],["58","المنيعة"]].map(x=>({code:x[0],name:x[1]}));
const seed={company:{name:"E-Com Pulse DZ Pro",currency:"DZD",defaultVat:19},products:[],orders:[],customers:[],carriers:[],shipments:[],stockMoves:[],integrations:[],expenses:[],employees:[],documents:[],audit:[],seq:1,wilayas:W};
async function init(){if(!pool){try{await fs.access("./data.json")}catch{await fs.writeFile("./data.json",JSON.stringify(seed))}}else await pool.query("create table if not exists app_state(id int primary key,data jsonb not null)");}
async function getDB(){if(pool){let r=await pool.query("select data from app_state where id=1");if(!r.rowCount){await pool.query("insert into app_state values(1,$1)",[seed]);return structuredClone(seed)}return r.rows[0].data}return JSON.parse(await fs.readFile("./data.json","utf8"))}
async function save(db){if(pool)await pool.query("update app_state set data=$1 where id=1",[db]);else await fs.writeFile("./data.json",JSON.stringify(db,null,2))}
const id=(db,p)=>p+"-"+String(db.seq++).padStart(7,"0"),num=x=>Number.isFinite(Number(x))?Number(x):0;
const send=(res,status,data)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-webhook-secret,x-shopify-hmac-sha256,x-wc-webhook-signature"});res.end(JSON.stringify(data))};
async function readBody(req){let s="";for await(const c of req)s+=c;if(s.length>10e6)throw Error("Payload too large");try{return s?JSON.parse(s):{}}catch{throw Error("Invalid JSON")}}
async function raw(req){let s="";for await(const c of req)s+=c;return s}
function audit(db,a,e,i,d=""){db.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action:a,entity:e,entityId:i,details:d})}
function headers(c){const h={"content-type":"application/json",accept:"application/json"};if(c.token)h.authorization="Bearer "+c.token;if(c.apiKey)h["x-api-key"]=c.apiKey;return h}
async function call(url,opt={}){const r=await fetch(url,{...opt,signal:AbortSignal.timeout(15000)}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok)throw Error("HTTP "+r.status+" "+JSON.stringify(d).slice(0,500));return d}
function carrierPayload(o){return{nom_client:o.customer||"",telephone:o.phone||"",telephone_2:o.phone2||"",adresse:o.address||"",code_wilaya:String(o.wilayaCode||o.wilaya||""),commune:o.commune||"",montant:num(o.total),produit:o.product||"Commande e-commerce",remarque:o.notes||"",weight:num(o.weight||1),reference:o.reference||o.id,type:1,stop_desk:o.stopDesk?1:0,fragile:o.fragile?1:0}}
async function dispatch(db,o,c){const root=String(c.baseUrl||"").replace(/\/+$/,"");if(!root)throw Error("Base URL مفقود");const p=String(c.provider||"custom").toLowerCase(),api=root.endsWith("/api/v1")?root:root+"/api/v1";let d;if(p.includes("ecotrack")||p.includes("aranex"))d=await call(api+"/create/order",{method:"POST",headers:headers(c),body:JSON.stringify(carrierPayload(o))});else{if(!c.createUrl)throw Error("Create URL مفقود لهذا المزود");d=await call(c.createUrl,{method:c.method||"POST",headers:headers(c),body:JSON.stringify(c.payloadTemplate?JSON.parse(JSON.stringify(c.payloadTemplate).replaceAll("{{customer}}",o.customer||"").replaceAll("{{phone}}",o.phone||"").replaceAll("{{amount}}",String(o.total||0)).replaceAll("{{address}}",o.address||"")):carrierPayload(o))})}const tracking=d.tracking||d.trackingNumber||d.tracking_number||d.data?.tracking||d.data?.trackingNumber||d.order?.tracking||d.id;if(!tracking)throw Error("لم تُرجع شركة التوصيل رقم Tracking");o.tracking=String(tracking);o.carrierId=c.id;o.status="SHIPPED";o.dispatchedAt=new Date().toISOString();db.shipments.unshift({id:id(db,"SHP"),orderId:o.id,carrierId:c.id,tracking:o.tracking,status:"SHIPPED",createdAt:new Date().toISOString()});if(!o.stockDeducted){for(const it of o.items||[]){const p=db.products.find(x=>x.id===it.productId);if(p){if(p.stock<num(it.quantity))throw Error("المخزون غير كافٍ: "+p.name);p.stock-=num(it.quantity);db.stockMoves.unshift({id:id(db,"STK"),productId:p.id,type:"OUT",quantity:num(it.quantity),reason:"Dispatch "+o.id,at:new Date().toISOString()})}}o.stockDeducted=true}audit(db,"DISPATCH","order",o.id,c.name+" / "+o.tracking);return o}
function normalize(db,a,source){const addr=a.shipping_address||a.billing_address||{},customer=a.customer?.first_name?([a.customer.first_name,a.customer.last_name].filter(Boolean).join(" ")):a.customer||a.customer_name||a.name||[a.first_name,a.last_name].filter(Boolean).join(" ")||addr.name||"",items=(a.line_items||a.items||a.products||[]).map(x=>({productId:x.product_id||x.productId||x.sku||"",name:x.name||x.title||"",quantity:num(x.quantity||1),unitPrice:num(x.price||x.unit_price||0)})),o={id:id(db,"ORD"),externalId:String(a.id||a.order_id||a.reference||""),source,customer,phone:a.phone||a.customer?.phone||addr.phone||"",address:a.address||addr.address1||addr.address||"",wilaya:a.wilaya||a.province||a.state||"",wilayaCode:a.wilayaCode||a.wilaya_code||"",commune:a.commune||a.city||addr.city||"",total:num(a.total_price||a.total||a.amount||a.montant),status:"NEW",notes:a.note||a.notes||"",items,createdAt:new Date().toISOString()};o.cogs=0;for(const it of items){const p=db.products.find(x=>x.sku&&it.productId&&x.sku===it.productId)||db.products.find(x=>x.name.toLowerCase()===it.name.toLowerCase());if(p){it.productId=p.id;it.cost=num(p.cost);o.cogs+=it.cost*it.quantity}}db.orders.unshift(o);audit(db,"IMPORT","order",o.id,source);return o}
function verify(req,secret,rawBody){if(!secret)return true;const supplied=req.headers["x-webhook-secret"]||req.headers["x-shopify-hmac-sha256"]||req.headers["x-wc-webhook-signature"]||"";if(supplied===secret)return true;try{const h=crypto.createHmac("sha256",secret).update(rawBody).digest("base64");return crypto.timingSafeEqual(Buffer.from(h),Buffer.from(String(supplied)))}catch{return false}}
const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>E-Com Pulse DZ Pro</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e7eefb;font-family:Arial,sans-serif}button,input,select{font:inherit}.app{display:flex;min-height:100vh}.side{width:250px;background:#101a2c;border-left:1px solid #24324a;padding:18px;position:sticky;top:0;height:100vh}.brand{font-weight:800;font-size:18px;margin-bottom:18px}.brand small{display:block;color:#7f93b5;font-size:10px;margin-top:6px}.nav button{display:block;width:100%;text-align:right;background:transparent;color:#b9c7df;border:0;padding:11px;border-radius:9px;cursor:pointer;margin:3px 0}.nav button.active,.nav button:hover{background:#1b2b46;color:#fff}.main{flex:1;padding:24px;max-width:1600px;margin:auto;width:100%}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:20px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #33435f;background:#172238;color:#fff;padding:9px 13px;border-radius:8px;cursor:pointer}.primary{background:#00a77d;border-color:#00a77d}.danger{background:#8b2635;border-color:#8b2635}.blue{background:#245ea8;border-color:#245ea8}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card,.panel{background:#111d31;border:1px solid #253550;border-radius:12px;padding:16px}.card b{font-size:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #253550;text-align:right}.table th{color:#8fa3c5}.scroll{overflow:auto}.modal{position:fixed;inset:0;background:#0009;display:flex;align-items:center;justify-content:center;padding:20px}.box{max-width:850px;width:100%;max-height:90vh;overflow:auto;background:#111d31;border:1px solid #344663;border-radius:14px;padding:20px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.form label{display:flex;flex-direction:column;gap:6px;color:#aebdd4}.form input{background:#0b1526;border:1px solid #344663;color:#fff;border-radius:8px;padding:9px}.hidden{display:none}.muted{color:#8da0bd}.code{direction:ltr;text-align:left;word-break:break-all;background:#09111e;padding:8px;border-radius:7px}@media(max-width:800px){.side{width:70px;padding:8px}.brand{font-size:0}.brand small{display:none}.nav span{display:none}.main{padding:12px}.form{grid-template-columns:1fr}}</style></head><body><div id="app"></div><div id="modal" class="modal hidden"></div><script>
const S={db:null,view:"dashboard"},$=s=>document.querySelector(s),money=x=>Number(x||0).toLocaleString("fr-DZ",{maximumFractionDigits:2})+" DZD";
async function api(p,o={}){const r=await fetch(p,{headers:{"content-type":"application/json"},...o}),d=await r.json();if(!r.ok)throw Error(d.error||"Erreur");return d}async function load(){S.db=(await api("/api/export")).db}
const nav=[["dashboard","🏠","Dashboard"],["orders","🛒","الطلبات"],["products","📦","المخزون"],["customers","👥","العملاء"],["carriers","🚚","شركات التوصيل"],["integrations","🔗","ربط المواقع"],["finance","💰","المالية"],["documents","🧾","الفواتير"],["employees","👨‍💼","الموظفون"]];
function shell(b){$("#app").innerHTML=`<div class="app"><aside class="side"><div class="brand">E-COM PULSE DZ PRO<small>ERP • ECOM • ALGÉRIE</small></div><div class="nav">${nav.map(x=>`<button class="${S.view===x[0]?"active":""}" onclick="go('${x[0]}')">${x[1]} <span>${x[2]}</span></button>`).join("")}</div></aside><main class="main"><div class="top"><div><h1>${nav.find(x=>x[0]===S.view)?.[2]||"Dashboard"}</h1><div class="muted">${S.db.company.name} • DZD</div></div><div class="actions"><button class="btn" onclick="backup()">نسخة احتياطية</button><button class="btn primary" onclick="addCurrent()">＋ إضافة</button></div></div>${b}</main></div>`}
async function go(v){S.view=v;await load();render()}function render(){const d=S.db;let b=S.view==="dashboard"?dashboard(d):S.view==="orders"?orders(d):S.view==="products"?products(d):S.view==="customers"?customers(d):S.view==="carriers"?carriers(d):S.view==="integrations"?integrations(d):S.view==="finance"?finance(d):S.view==="documents"?documents(d):employees(d);shell(b)}
function dashboard(d){const rev=d.orders.filter(x=>x.status==="DELIVERED").reduce((a,x)=>a+Number(x.total||0),0),sv=d.products.reduce((a,x)=>a+Number(x.stock||0)*Number(x.cost||0),0);return `<div class="cards"><div class="card">الطلبات<br><b>${d.orders.length}</b></div><div class="card">تم التسليم<br><b>${d.orders.filter(x=>x.status==="DELIVERED").length}</b></div><div class="card">المبيعات المسلمة<br><b>${money(rev)}</b></div><div class="card">قيمة المخزون<br><b>${money(sv)}</b></div><div class="card">منخفض المخزون<br><b>${d.products.filter(x=>Number(x.stock)<=Number(x.minStock||0)).length}</b></div></div><div class="grid" style="margin-top:14px"><div class="panel"><h3>حالة الطلبات</h3>${Object.entries(d.orders.reduce((a,o)=>(a[o.status]=(a[o.status]||0)+1,a),{})).map(x=>`<p>${x[0]}: <b>${x[1]}</b></p>`).join("")||"لا توجد طلبات"}</div><div class="panel"><h3>آخر العمليات</h3>${d.audit.slice(0,8).map(x=>`<p class="muted">${x.at.slice(0,19)} — ${x.action} — ${x.entityId}</p>`).join("")}</div></div>`}
function table(h,r){return `<div class="panel scroll"><table class="table"><thead><tr>${h.map(x=>"<th>"+x+"</th>").join("")}</tr></thead><tbody>${r}</tbody></table></div>`}
function orders(d){return table(["ID","العميل","المبلغ","الحالة","المصدر","Tracking",""],d.orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${money(o.total)}</td><td>${o.status}</td><td>${o.source||"manual"}</td><td>${o.tracking||"—"}</td><td><button class="btn blue" onclick="orderAction('${o.id}')">إدارة</button></td></tr>`).join(""))}
function products(d){return table(["SKU","المنتج","المخزون","التكلفة","السعر",""],d.products.map(p=>`<tr><td>${p.sku||"—"}</td><td>${p.name}</td><td>${p.stock}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td><button class="btn" onclick="stock('${p.id}',1)">＋</button> <button class="btn" onclick="stock('${p.id}',-1)">−</button> <button class="btn" onclick="editProduct('${p.id}')">✏️</button> <button class="btn danger" onclick="del('products','${p.id}')">🗑</button></td></tr>`).join(""))}
function customers(d){return table(["ID","العميل","الهاتف","الولاية"],d.customers.map(c=>`<tr><td>${c.id}</td><td>${c.name}</td><td>${c.phone}</td><td>${c.wilaya||""}</td></tr>`).join(""))}
function carriers(d){return `<div class="panel"><p class="muted">EcoTrack/Aranex: Base URL + Bearer Token. الشركات الأخرى: Base URL/Create URL + بيانات API الخاصة بها.</p><button class="btn primary" onclick="addCarrier()">＋ شركة توصيل</button></div>`+table(["الشركة","Provider","Base URL",""],d.carriers.map(c=>`<tr><td>${c.name}</td><td>${c.provider||"custom"}</td><td class="code">${c.baseUrl||""}</td><td><button class="btn" onclick="testCarrier('${c.id}')">اختبار</button> <button class="btn" onclick="editCarrier('${c.id}')">تعديل</button> <button class="btn danger" onclick="del('carriers','${c.id}')">حذف</button></td></tr>`).join(""))}
function integrations(d){return `<div class="panel"><h3>Shopify / WooCommerce / SetShop / YouCan / Landing Page / Custom API</h3><p>أنشئ Webhook ثم ضع الرابط والـSecret في منصة متجرك. كل طلب جديد سيدخل تلقائيًا إلى النظام.</p><button class="btn primary" onclick="addIntegration()">＋ إنشاء Webhook</button></div>`+table(["المنصة","المتجر","Webhook URL","Secret"],d.integrations.map(i=>`<tr><td>${i.platform}</td><td>${i.name}</td><td class="code">${location.origin}/webhooks/orders/${i.id}</td><td class="code">${i.secret}</td></tr>`).join(""))}
function finance(d){return `<div class="cards"><div class="card">المصاريف<br><b>${money(d.expenses.reduce((a,x)=>a+Number(x.amount||0),0))}</b></div><div class="card">الموظفون<br><b>${d.employees.length}</b></div></div>`+table(["المصروف","المبلغ"],d.expenses.map(x=>`<tr><td>${x.name}</td><td>${money(x.amount)}</td></tr>`).join(""))}
function documents(d){return table(["الرقم","النوع","العميل","المبلغ"],d.documents.map(x=>`<tr><td>${x.number}</td><td>${x.type}</td><td>${x.customer}</td><td>${money(x.total)}</td></tr>`).join(""))}
function employees(d){return table(["ID","الموظف","الدور","الراتب"],d.employees.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.role||""}</td><td>${money(x.salary)}</td></tr>`).join(""))}
function modal(t,c){$("#modal").classList.remove("hidden");$("#modal").innerHTML=`<div class="box"><h2>${t}</h2>${c}<br><button class="btn" onclick="closeModal()">إغلاق</button></div>`}function closeModal(){$("#modal").classList.add("hidden")}
async function addIntegration(){modal("ربط موقع جديد",`<div class="form"><label>المنصة<input id="ip" value="Shopify"></label><label>اسم المتجر<input id="in"></label></div><br><button class="btn primary" onclick="saveIntegration()">إنشاء</button>`)}
async function saveIntegration(){const x=await api("/api/integrations",{method:"POST",body:JSON.stringify({platform:$("#ip").value,name:$("#in").value})});modal("تم الإنشاء",`<p>Webhook URL</p><div class="code">${location.origin}${x.webhookPath}</div><p>Secret</p><div class="code">${x.secret}</div>`);await load();render()}
async function addCarrier(){modal("شركة توصيل",`<div class="form"><label>الاسم<input id="cn"></label><label>Provider<input id="cp" value="ecotrack"></label><label>Base URL<input id="cu"></label><label>API Token<input id="ct" type="password"></label><label>Create URL<input id="cc"></label></div><br><button class="btn primary" onclick="saveCarrier()">حفظ</button>`)}
async function saveCarrier(){await api("/api/carriers",{method:"POST",body:JSON.stringify({name:$("#cn").value,provider:$("#cp").value,baseUrl:$("#cu").value,token:$("#ct").value,createUrl:$("#cc").value})});closeModal();await load();render()}
async function testCarrier(id){try{const x=await api("/api/carriers/"+id+"/test",{method:"POST"});alert("نجح الاتصال HTTP "+x.status)}catch(e){alert(e.message)}}
async function editCarrier(id){const c=S.db.carriers.find(x=>x.id===id);modal("تعديل شركة",`<div class="form"><label>الاسم<input id="cn" value="${c.name||""}"></label><label>Provider<input id="cp" value="${c.provider||""}"></label><label>Base URL<input id="cu" value="${c.baseUrl||""}"></label><label>API Token<input id="ct" type="password"></label><label>Create URL<input id="cc" value="${c.createUrl||""}"></label></div><br><button class="btn primary" onclick="updateCarrier('${id}')">حفظ</button>`)}
async function updateCarrier(id){const b={name:$("#cn").value,provider:$("#cp").value,baseUrl:$("#cu").value,createUrl:$("#cc").value};if($("#ct").value)b.token=$("#ct").value;await api("/api/carriers/"+id,{method:"PATCH",body:JSON.stringify(b)});closeModal();await load();render()}
async function stock(id,s){const q=prompt(s>0?"كمية الإضافة؟":"كمية النقص؟");if(!q)return;await api("/api/stock",{method:"POST",body:JSON.stringify({productId:id,type:s>0?"IN":"OUT",quantity:Number(q),reason:"تعديل يدوي"})});await load();render()}
async function editProduct(id){const p=S.db.products.find(x=>x.id===id);modal("تعديل المنتج",`<div class="form"><label>الاسم<input id="pn" value="${p.name||""}"></label><label>SKU<input id="ps" value="${p.sku||""}"></label><label>التكلفة<input id="pc" type="number" value="${p.cost||0}"></label><label>السعر<input id="pp" type="number" value="${p.price||0}"></label><label>المخزون<input id="px" type="number" value="${p.stock||0}"></label><label>الحد الأدنى<input id="pm" type="number" value="${p.minStock||0}"></label></div><br><button class="btn primary" onclick="updateProduct('${id}')">حفظ</button>`)}
async function updateProduct(id){await api("/api/products/"+id,{method:"PATCH",body:JSON.stringify({name:$("#pn").value,sku:$("#ps").value,cost:Number($("#pc").value),price:Number($("#pp").value),stock:Number($("#px").value),minStock:Number($("#pm").value)})});closeModal();await load();render()}
async function createProduct(){await api("/api/products",{method:"POST",body:JSON.stringify({name:$("#pn").value,sku:$("#ps").value,cost:Number($("#pc").value),price:Number($("#pp").value),stock:Number($("#px").value),minStock:Number($("#pm").value)})});closeModal();await load();render()}
function addCurrent(){if(S.view==="products")modal("منتج جديد",`<div class="form"><label>الاسم<input id="pn"></label><label>SKU<input id="ps"></label><label>التكلفة<input id="pc" type="number"></label><label>السعر<input id="pp" type="number"></label><label>المخزون<input id="px" type="number" value="0"></label><label>الحد الأدنى<input id="pm" type="number" value="0"></label></div><br><button class="btn primary" onclick="createProduct()">حفظ</button>`);else if(S.view==="carriers")addCarrier();else if(S.view==="integrations")addIntegration();else alert("هذه الشاشة لا تحتوي إضافة سريعة بعد")}
async function orderAction(id){const o=S.db.orders.find(x=>x.id===id);modal("إدارة "+id,`<p>العميل: <b>${o.customer}</b></p><p>المبلغ: <b>${money(o.total)}</b></p><p>Tracking: <b>${o.tracking||"—"}</b></p><div class="actions">${S.db.carriers.map(c=>`<button class="btn blue" onclick="dispatch('${id}','${c.id}')">Dispatch عبر ${c.name}</button>`).join("")}</div><br><button class="btn danger" onclick="del('orders','${id}')">حذف</button>`)}
async function dispatch(oid,cid){try{const x=await api("/api/orders/"+oid+"/dispatch",{method:"POST",body:JSON.stringify({carrierId:cid})});alert("تم Dispatch — Tracking: "+x.order.tracking);closeModal();await load();render()}catch(e){alert(e.message)}}
async function del(t,id){if(!confirm("تأكيد الحذف؟"))return;await api("/api/"+t+"/"+id,{method:"DELETE"});await load();render()}function backup(){const a=document.createElement("a");a.href="/api/backup";a.download="ecom-pulse-backup.json";a.click()}
(async()=>{await load();render()})()</script></body></html>`;
async function route(req,res){const u=new URL(req.url,"http://localhost"),p=u.pathname;if(req.method==="OPTIONS")return send(res,204,{});if(req.method==="GET"&&p==="/"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});return res.end(html)}const db=await getDB();
if(req.method==="GET"&&p==="/api/health")return send(res,200,{ok:true,version:"4.0.0",database:pool?"postgresql":"local"});if(req.method==="GET"&&p==="/api/export")return send(res,200,{db});if(req.method==="GET"&&p==="/api/backup"){res.writeHead(200,{"content-type":"application/json","content-disposition":"attachment; filename=ecom-pulse-backup.json"});return res.end(JSON.stringify(db,null,2))}if(req.method==="GET"&&p==="/api/wilayas")return send(res,200,W);
if(req.method==="POST"&&p.startsWith("/webhooks/orders/")){const iid=p.split("/").pop(),rawBody=await raw(req),i=db.integrations.find(x=>x.id===iid);if(!i)return send(res,404,{error:"Integration not found"});if(!verify(req,i.secret,rawBody))return send(res,401,{error:"Invalid signature"});let payload;try{payload=JSON.parse(rawBody)}catch{return send(res,400,{error:"Invalid JSON"})}const o=normalize(db,payload,i.platform);await save(db);return send(res,200,{ok:true,orderId:o.id})}
if(req.method==="POST"&&p==="/api/integrations"){const b=await readBody(req),x={id:id(db,"INT"),name:b.name||b.platform||"Store",platform:b.platform||"custom",secret:crypto.randomBytes(24).toString("hex"),enabled:true,createdAt:new Date().toISOString()};db.integrations.unshift(x);audit(db,"CREATE","integration",x.id);await save(db);return send(res,201,{...x,webhookPath:"/webhooks/orders/"+x.id})}
const m=p.match(/^\/api\/(carriers|products|orders|customers|employees|expenses|documents|integrations)(?:\/([^/]+))?(?:\/(test|dispatch))?$/);if(m){const type=m[1],key=m[2],action=m[3],arr=db[type];if(req.method==="GET")return send(res,200,key?arr.find(x=>x.id===key)||null:arr);if(req.method==="DELETE"&&key){const i=arr.findIndex(x=>x.id===key);if(i<0)return send(res,404,{error:"Not found"});arr.splice(i,1);audit(db,"DELETE",type,key);await save(db);return send(res,200,{ok:true})}if(req.method==="POST"&&action==="test"&&type==="carriers"){const c=arr.find(x=>x.id===key);if(!c)return send(res,404,{error:"Not found"});try{const root=String(c.baseUrl||"").replace(/\/+$/,""),p=String(c.provider||"").toLowerCase(),url=p.includes("ecotrack")||p.includes("aranex")?(root.endsWith("/api/v1")?root:root+"/api/v1")+"/validate/token":(c.testUrl||root),d=await call(url,{headers:headers(c)});return send(res,200,{ok:true,status:200,data:d})}catch(e){return send(res,400,{ok:false,error:e.message})}}if(req.method==="POST"&&action==="dispatch"&&type==="orders"){const b=await readBody(req),o=arr.find(x=>x.id===key),c=db.carriers.find(x=>x.id===b.carrierId);if(!o||!c)return send(res,404,{error:"Order/carrier not found"});try{await dispatch(db,o,c);await save(db);return send(res,200,{ok:true,order:o})}catch(e){return send(res,400,{error:e.message})}}if(req.method==="POST"&&!action){const b=await readBody(req),prefix={products:"PRD",orders:"ORD",carriers:"CAR",customers:"CUS",employees:"EMP",expenses:"EXP",documents:"DOC",integrations:"INT"}[type]||"GEN",x={...b,id:id(db,prefix),createdAt:new Date().toISOString()};if(type==="products"){x.stock=num(x.stock);x.cost=num(x.cost);x.price=num(x.price);x.minStock=num(x.minStock)}if(type==="orders"){x.total=num(x.total);x.status=x.status||"NEW";x.items=x.items||[]}arr.unshift(x);audit(db,"CREATE",type,x.id);await save(db);return send(res,201,x)}if(req.method==="PATCH"&&key){const i=arr.findIndex(x=>x.id===key);if(i<0)return send(res,404,{error:"Not found"});arr[i]={...arr[i],...(await readBody(req)),updatedAt:new Date().toISOString()};await save(db);return send(res,200,arr[i])}}
if(req.method==="POST"&&p==="/api/stock"){const b=await readBody(req),x=db.products.find(x=>x.id===b.productId);if(!x)return send(res,404,{error:"Product not found"});const q=num(b.quantity);if(q<=0)return send(res,400,{error:"كمية غير صحيحة"});if(b.type==="OUT"&&num(x.stock)<q)return send(res,400,{error:"المخزون غير كافٍ"});x.stock=num(x.stock)+(b.type==="OUT"?-q:q);db.stockMoves.unshift({id:id(db,"STK"),productId:x.id,type:b.type,quantity:q,reason:b.reason||"",at:new Date().toISOString()});audit(db,"STOCK","product",x.id,b.type+" "+q);await save(db);return send(res,200,x)}return send(res,404,{error:"Not found"})}
await init();http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);send(res,500,{error:e.message})})).listen(PORT,"0.0.0.0",()=>console.log("E-Com Pulse DZ Pro 4.0 on "+PORT));